query getSermon($sermonId: Int!) {
  content(id: $sermonId) {
    entryId: id
    title
    status
    channelName
    meta {
      urlTitle
      siteId
      date
      actualDate
      channelId
    }
    content {
      description
      speakers
      ooyalaId
    }
  }
}
