
export default {
  SET_VISIBILITY: "AUDIO.SET_VISIBILITY",
  SET_ORDER: "AUDIO.SET_ORDER",
  SET_STATE: "AUDIO.SET_STATE",
  SET_SEEK: "AUDIO.SET_SEEK",
  SET_PROGRESS: "AUDIO.SET_PROGRESS",
  SET_PLAYLIST: "AUDIO.SET_PLAYLIST",
  ADD_TO_PLAYLIST: "AUDIO.ADD_TO_PLAYLIST",
  SET_PLAYING: "AUDIO.SET_PLAYING",
  SET_REPEAT: "AUDIO.SET_REPEAT",
  RESET_ALL: "AUDIO.RESET_ALL",
}
