export default {
  SET_PROGRESS: "GIVE.SET_PROGRESS",
  STEP_PROGRESS: "GIVE.STEP_PROGRESS",

  SET_SAVED_ACCOUNT: "GIVE.SET_SAVED_ACCOUNT",

  ADD_TRANSACTION: "GIVE.ADD_TRANSACTION",
  CLEAR_TRANSACTION: "GIVE.CLEAR_TRANSACTION",
  CLEAR_TRANSACTIONS: "GIVE.CLEAR_TRANSACTIONS",

  SAVE_DATA: "GIVE.SAVE_DATA",
  REMOVE_DATA: "GIVE.REMOVE_DATA",
  CLEAR_DATA: "GIVE.CLEAR_DATA",

  SAVE_SCHEDULE_DATA: "GIVE.SAVE_SCHEDULE_DATA",
  SAVE_SCHEDULES: "GIVE.SAVE_SCHEDULES",
  REMOVE_SCHEDULE: "GIVE.REMOVE_SCHEDULE",
  REMOVE_SCHEDULE_DATA: "GIVE.REMOVE_SCHEDULE_DATA",

  SET_STATE: "GIVE.SET_STATE",
  SET_ERROR: "GIVE.SET_ERROR",

  REMOVE_ERROR: "GIVE.REMOVE_ERROR",
  SET_ERRORS: "GIVE.SET_ERRORS",

  SET_SUCCESS: "GIVE.SET_SUCCESS",

  SET_ACCOUNTS: "GIVE.SET_ACCOUNTS",

  SET_TRANSACTION_TYPE: "GIVE.SET_TRANSACTION_TYPE",

  SET_TRANSACTION_DETAILS: "GIVE.SET_TRANSACTION_DETAILS",

  SET_REMINDER_DATE: "GIVE.SET_REMINDER_DATE",
}
