#!/bin/bash
set -e

GREEN='\033[0;32m'
NO_COLOR='\033[0m'

BUILD_TAG="GH$TRAVIS_PULL_REQUEST-B$TRAVIS_BUILD_ID"

openssl aes-256-cbc -K $encrypted_de5ad5555d6e_key -iv $encrypted_de5ad5555d6e_iv -in .travis/ci.enc -out ~/.ssh/id_rsa -d
chmod 600 ~/.ssh/id_rsa
eval `ssh-agent -s`
ssh-add ~/.ssh/id_rsa

REPO=`git config remote.origin.url`
SSH_REPO=${REPO/https:\/\/github.com\//git@github.com:}

git config user.name "Travis CI"
git config user.email "$COMMIT_AUTHOR_EMAIL"

git tag $BUILD_TAG
git push -q $SSH_REPO --tags

echo "Pushed Tag: ${GREEN}$BUILD_TAG${NO_COLOR} to Github!"


