
export default {
  SET_ACCOUNT_STATUS: "ONBOARD.SET_ACCOUNT_STATUS",
  SET_DATA: "ONBOARD.SET_DATA",
  REMOVE_DATA: "ONBOARD.REMOVE_DATA",
  SET_FORGOT: "ONBOARD.SET_FORGOT",
  SET_STATE: "ONBOARD.SET_STATE",
  SET_ERROR: "ONBOARD.SET_ERROR",
  REMOVE_ERROR: "ONBOARD.REMOVE_ERROR",
  SET_ERRORS: "ONBOARD.SET_ERRORS",
  REMOVE_ERRORS: "ONBOARD.REMOVE_ERRORS",
  SET_SUCCESS: "ONBOARD.SET_SUCCESS",
  IS_AUTHORIZED: "ONBOARD.IS_AUTHORIZED",
  SET_PERSON: "ONBOARD.SET_PERSON"
}
