query getFeed($excludeChannels: [String]!, $limit: Int!, $skip: Int!){
  feed(excludeChannels: $excludeChannels, limit: $limit, skip: $skip, cache: false) {
    entryId: id
    title
    channelName
    collectionId
    status
    meta {
      siteId
      date
      channelId
    }
    content {
      images {
        fileName
        fileType
        fileLabel
        s3
        cloudfront
      }
      colors {
        id
        value
        description
      }
    }
  }
}
